openapi: 3.0.2
info:
  contact:
    email: support@phoenixnap.com
    name: PhoenixNAP Team
    url: https://phoenixnap.com/
  description: "Create, list, edit and delete public/private networks with the Network\
    \ API. Use public networks to place multiple \nservers on the same network or\
    \ VLAN. Assign new servers with IP addresses from the same CIDR range. Use private\
    \ \nnetworks to avoid unnecessary egress data charges. Model your networks according\
    \ to your business needs.<br>\n<br>\n<span class='pnap-api-knowledge-base-link'>\n\
    Helpful knowledge base articles are available for \n<a href='https://phoenixnap.com/kb/bmc-server-management-via-api#multi-private-backend-network-api'\
    \ target='_blank'>multi-private backend networks</a>\nand <a href='https://phoenixnap.com/kb/bmc-server-management-via-api#ftoc-heading-15'\
    \ target='_blank'>public networks</a>.\n</span><br>\n<br>\n<b>All URLs are relative\
    \ to (https://api.phoenixnap.com/networks/v1/)</b>\n"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://phoenixnap.com/infrastructure-solutions/legal-it/privacy-shield-compliant-privacy-policy
  title: Networks API
  version: "1.0"
servers:
- url: https://api.phoenixnap.com/networks/v1
security:
- OAuth2:
  - bmc
  - bmc.read
tags:
- description: Private Network operations
  name: Private Networks
- description: Public networks operations
  name: Public Networks
paths:
  /private-networks:
    get:
      description: List all Private Networks owned by account.
      operationId: privateNetworksGet
      parameters:
      - description: If present will filter the result by the given location of the
          Private Networks.
        example: PHX
        explode: true
        in: query
        name: location
        required: false
        schema:
          description: "Supported values are `PHX`, `ASH`, `SGP`, `NLD`, `CHI`, `SEA`\
            \ and `AUS`."
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              example:
              - id: 604724a5a807f2d3be8660c7
                name: My Default Backend Network
                type: PRIVATE
                location: PHX
                locationDefault: true
                vlanId: 10
                description: My Default Backend Network
                cidr: 10.0.0.0/24
                servers:
                - id: 603f3e995c18d515cda9c4f8
                  ips:
                  - 10.0.0.2
                  - 10.0.0.3
                memberships:
                - resourceId: 603f3e995c18d515cda9c4f8
                  resourceType: server
                  ips:
                  - 10.0.0.2
                  - 10.0.0.3
                status: READY
                createdOn: 2022-04-07T13:20:30.491Z
              - id: 604724ac9ed2abd18e9f1cb6
                name: My Additional Backend Network
                type: PRIVATE
                location: PHX
                locationDefault: false
                vlanId: 11
                description: My Additional Backend Network
                cidr: 10.0.0.0/24
                servers:
                - id: 603f3e995c18d515cdvte548
                  ips:
                  - 10.0.0.4
                  - 10.0.0.5
                memberships:
                - resourceId: 603f3e995c18d515cdvte548
                  resourceType: server
                  ips:
                  - 10.0.0.4
                  - 10.0.0.5
                status: READY
                createdOn: 2022-04-07T13:20:30.491Z
              schema:
                items:
                  $ref: '#/components/schemas/PrivateNetwork'
                type: array
          description: List of all the Private Networks owned by account.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to wrong data. Please check the provided
            parameters and try again.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to invalid credentials. Please check
            the provided credentials and try again.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since this resource cannot be accessed by
            the provided credentials.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - OAuth2:
        - bmc.read
      summary: List Private Networks.
      tags:
      - Private Networks
    post:
      description: Create a Private Network.
      operationId: privateNetworksPost
      requestBody:
        content:
          application/json:
            examples:
              PrivateNetworkCreateDefault:
                value:
                  name: My Default Backend Network
                  location: PHX
                  locationDefault: true
                  description: My Default Backend Network
                  cidr: 10.0.0.0/24
              PrivateNetworkCreateNonDefault:
                value:
                  name: My Additional Backend Network
                  location: PHX
                  locationDefault: false
                  description: My Additional Backend Network
                  cidr: 10.0.0.0/24
            schema:
              $ref: '#/components/schemas/PrivateNetworkCreate'
      responses:
        "201":
          content:
            application/json:
              examples:
                PrivateNetworkDefaultCreated:
                  value:
                    id: 604724a5a807f2d3be8660c7
                    name: My Default Backend Network
                    type: PRIVATE
                    location: PHX
                    locationDefault: true
                    vlanId: 10
                    description: My Default Backend Network
                    cidr: 10.0.0.0/24
                    servers: []
                    memberships: []
                    status: READY
                    createdOn: 2022-04-07T13:20:30.491Z
                PrivateNetworkNonDefaultCreated:
                  value:
                    id: 604724ac9ed2abd18e9f1cb6
                    name: My Additional Backend Network
                    type: PRIVATE
                    location: PHX
                    locationDefault: false
                    vlanId: 11
                    description: My Additional Backend Network
                    cidr: 10.0.0.0/24
                    servers: []
                    memberships: []
                    status: READY
                    createdOn: 2022-04-07T13:20:30.491Z
              schema:
                $ref: '#/components/schemas/PrivateNetwork'
          description: Private Network successfully created.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to wrong data. Please check the provided
            parameters and try again.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to invalid credentials. Please check
            the provided credentials and try again.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since this resource cannot be accessed by
            the provided credentials.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - OAuth2:
        - bmc
      summary: Create a Private Network.
      tags:
      - Private Networks
  /private-networks/{privateNetworkId}:
    delete:
      description: Delete Private Network.
      operationId: privateNetworksNetworkIdDelete
      parameters:
      - description: The private network identifier.
        example: 603f3b2cfcaf050643b89a4b
        explode: false
        in: path
        name: privateNetworkId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Private Network deleted.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to wrong data. Please check the provided
            parameters and try again.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to invalid credentials. Please check
            the provided credentials and try again.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since this resource cannot be accessed by
            the provided credentials.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - OAuth2:
        - bmc
      summary: Delete a Private Network.
      tags:
      - Private Networks
    get:
      description: Retrieve Private Network Details.
      operationId: privateNetworksNetworkIdGet
      parameters:
      - description: The private network identifier.
        example: 603f3b2cfcaf050643b89a4b
        explode: false
        in: path
        name: privateNetworkId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                DefaultPrivateNetwork:
                  value:
                    id: 604724a5a807f2d3be8660c7
                    name: My Default Backend Network
                    type: PRIVATE
                    location: PHX
                    locationDefault: true
                    vlanId: 10
                    description: My Default Backend Network
                    cidr: 10.0.0.0/24
                    servers:
                    - id: 603f3e995c18d515cda9c4f8
                      ips:
                      - 10.0.0.2
                      - 10.0.0.3
                    memberships:
                    - resourceId: 603f3e995c18d515cda9c4f8
                      resourceType: server
                      ips:
                      - 10.0.0.2
                      - 10.0.0.3
                    status: READY
                    createdOn: 2022-04-07T13:20:30.491Z
                AdditionalPrivateNetwork:
                  value:
                    id: 604724ac9ed2abd18e9f1cb6
                    name: My Additional Backend Network
                    type: PRIVATE
                    location: PHX
                    locationDefault: false
                    vlanId: 11
                    description: My Additional Backend Network
                    cidr: 10.0.0.0/24
                    servers:
                    - id: 603f3e995c18d515cdvte548
                      ips:
                      - 10.0.0.4
                      - 10.0.0.5
                    memberships:
                    - resourceId: 603f3e995c18d515cdvte548
                      resourceType: server
                      ips:
                      - 10.0.0.4
                      - 10.0.0.5
                    status: READY
                    createdOn: 2022-04-07T13:20:30.491Z
              schema:
                $ref: '#/components/schemas/PrivateNetwork'
          description: Private Network Details.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to invalid credentials. Please check
            the provided credentials and try again.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since this resource cannot be accessed by
            the provided credentials.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since the resource could not been found.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - OAuth2:
        - bmc.read
      summary: Get a Private Network.
      tags:
      - Private Networks
    put:
      description: Update Private Network Details.
      operationId: privateNetworksNetworkIdPut
      parameters:
      - description: The private network identifier.
        example: 603f3b2cfcaf050643b89a4b
        explode: false
        in: path
        name: privateNetworkId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            examples:
              PrivateNetworkDefaultUpdate:
                value:
                  name: My Default Backend Network
                  description: My Default Backend Network
                  locationDefault: true
              PrivateNetworkNonDefaultUpdate:
                value:
                  name: My Additional Backend Network
                  description: My Additional Backend Network
                  locationDefault: false
            schema:
              $ref: '#/components/schemas/PrivateNetworkModify'
      responses:
        "200":
          content:
            application/json:
              examples:
                PrivateNetworkDefaultModified:
                  value:
                    id: 604724a5a807f2d3be8660c7
                    name: My Default Backend Network
                    type: PRIVATE
                    location: PHX
                    locationDefault: true
                    vlanId: 10
                    description: My Default Backend Network
                    cidr: 10.0.0.0/24
                    servers:
                    - id: 603f3e995c18d515cda9c4f8
                      ips:
                      - 10.0.0.2
                      - 10.0.0.3
                    memberships:
                    - resourceId: 603f3e995c18d515cda9c4f8
                      resourceType: server
                      ips:
                      - 10.0.0.2
                      - 10.0.0.3
                    status: READY
                    createdOn: 2022-04-07T13:20:30.491Z
                PrivateNetworkNonDefaultModified:
                  value:
                    id: 604724ac9ed2abd18e9f1cb6
                    name: My Additional Backend Network
                    type: PRIVATE
                    location: PHX
                    locationDefault: false
                    vlanId: 11
                    description: My Additional Backend Network
                    cidr: 10.0.0.0/24
                    servers:
                    - id: 603f3e995c18d515cdvte548
                      ips:
                      - 10.0.0.4
                      - 10.0.0.5
                    memberships:
                    - resourceId: 603f3e995c18d515cdvte548
                      resourceType: server
                      ips:
                      - 10.0.0.4
                      - 10.0.0.5
                    status: READY
                    createdOn: 2022-04-07T13:20:30.491Z
              schema:
                $ref: '#/components/schemas/PrivateNetwork'
          description: Private Network successfully updated.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to wrong data. Please check the provided
            parameters and try again.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to invalid credentials. Please check
            the provided credentials and try again.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since this resource cannot be accessed by
            the provided credentials.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since the resource could not been found.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - OAuth2:
        - bmc
      summary: Update a Private Network.
      tags:
      - Private Networks
  /public-networks:
    get:
      description: List all Public Networks owned by account.
      operationId: publicNetworksGet
      parameters:
      - description: If present will filter the result by the given location of the
          Public Networks.
        example: PHX
        explode: true
        in: query
        name: location
        required: false
        schema:
          description: "Supported values are `PHX`, `ASH`, `SGP`, `NLD`, `CHI`, `SEA`\
            \ and `AUS`."
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              example:
              - id: 60472f76bbadb4f36541d2fd
                name: Initial public network
                location: PHX
                description: "My first public network #1"
                ipBlocks:
                - id: 60473a6115e34466c9f8f083
                - id: 616e6ec6d66b406a45ab8797
                - id: 617d2d128bacbb05aca2caeb
                - id: 617d2da78bacbb05aca2caef
                - id: 618e5383a835704f8c59522d
                - id: 617d2f834dcf2869f8e4ef0b
                - id: 5f325c71b8a7ef1473e3c85b
                - id: 5ff5cc9bc1acf144d9106233
                - id: 610001e7da283e36d0a0df9f
                - id: 613b51c01f4b04615ba1d3be
                vlanId: 10
                createdOn: 2022-04-05T13:50:30.491Z
                status: READY
                memberships:
                - resourceId: 6128d3754b478b76ee8b3cdd
                  resourceType: server
                  ips:
                  - 10.111.14.110
                  - 10.111.14.115
                  - 10.111.14.136
                - resourceId: 5feae6b0b00bfb14eda82fc7
                  resourceType: server
                  ips:
                  - 10.111.14.121
              - id: 6123b97643046b5bffb1d7c3
                name: My additional public network
                location: PHX
                description: "My second public network #2"
                ipBlocks: []
                vlanId: 11
                status: READY
                createdOn: 2022-04-05T13:50:30.491Z
                memberships: []
              schema:
                items:
                  $ref: '#/components/schemas/PublicNetwork'
                type: array
          description: List of all the Public Networks owned by account.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to wrong data. Please check the provided
            parameters and try again.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to invalid credentials. Please check
            the provided credentials and try again.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since this resource cannot be accessed by
            the provided credentials.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - OAuth2:
        - bmc.read
      summary: List Public Networks.
      tags:
      - Public Networks
    post:
      description: Create a public network.
      operationId: publicNetworksPost
      requestBody:
        content:
          application/json:
            examples:
              PublicNetworkCreationWithOnlyRequiredField:
                value:
                  name: Initial public network
                  location: PHX
              PublicNetworkCreationOnlyWithoutIpBlocks:
                value:
                  name: Initial public network
                  location: PHX
                  description: "My first public network #1"
              PublicNetworkCreationWithAllParameters:
                value:
                  name: Initial public network
                  location: PHX
                  description: "My first public network #1"
                  ipBlocks:
                  - id: 60473a6115e34466c9f8f083
                  - id: 616e6ec6d66b406a45ab8797
                  - id: 617d2d128bacbb05aca2caeb
                  - id: 617d2da78bacbb05aca2caef
                  - id: 618e5383a835704f8c59522d
                  - id: 617d2f834dcf2869f8e4ef0b
                  - id: 5f325c71b8a7ef1473e3c85b
                  - id: 5ff5cc9bc1acf144d9106233
                  - id: 610001e7da283e36d0a0df9f
                  - id: 613b51c01f4b04615ba1d3be
            schema:
              $ref: '#/components/schemas/PublicNetworkCreate'
      responses:
        "201":
          content:
            application/json:
              examples:
                PublicNetworkWithOnlyRequiredFields:
                  value:
                    id: 60472f76bbadb4f36541d2fd
                    name: Initial public network
                    location: PHX
                    ipBlocks: []
                    vlanId: 10
                    status: READY
                    createdOn: 2022-04-05T13:50:30.491Z
                    memberships: []
                PublicNetworkOnlyWithoutIpBlocks:
                  value:
                    id: 60472f76bbadb4f36541d2fd
                    name: Initial public network
                    location: PHX
                    description: "My first public network #1"
                    ipBlocks: []
                    vlanId: 10
                    status: READY
                    createdOn: 2022-04-05T13:50:30.491Z
                    memberships: []
                PublicNetworkWithAllParameters:
                  value:
                    id: 60472f76bbadb4f36541d2fd
                    name: Initial public network
                    location: PHX
                    description: "My first public network #1"
                    ipBlocks:
                    - id: 60473a6115e34466c9f8f083
                    - id: 616e6ec6d66b406a45ab8797
                    - id: 617d2d128bacbb05aca2caeb
                    - id: 617d2da78bacbb05aca2caef
                    - id: 618e5383a835704f8c59522d
                    - id: 617d2f834dcf2869f8e4ef0b
                    - id: 5f325c71b8a7ef1473e3c85b
                    - id: 5ff5cc9bc1acf144d9106233
                    - id: 610001e7da283e36d0a0df9f
                    - id: 613b51c01f4b04615ba1d3be
                    vlanId: 10
                    status: READY
                    createdOn: 2022-04-05T13:50:30.491Z
                    memberships: []
              schema:
                $ref: '#/components/schemas/PublicNetwork'
          description: Network successfully created.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to wrong data. Please check the provided
            parameters and try again.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to invalid credentials. Please check
            the provided credentials and try again.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since this resource cannot be accessed by
            the provided credentials.
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The resource is in an incompatible state.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - OAuth2:
        - bmc
      summary: Create a public network.
      tags:
      - Public Networks
  /public-networks/{publicNetworkId}:
    delete:
      description: Delete Public Network. The request is accepted only if no resources
        are members of this network. The IP Block(s) will be freed and can be re-used
        in the future.
      operationId: publicNetworksNetworkIdDelete
      parameters:
      - description: The Public Network identifier.
        example: 603f3b2cfcaf050643b89a4b
        explode: false
        in: path
        name: publicNetworkId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: The Public Network has been deleted.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to wrong data. Please check the provided
            parameters and try again.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to invalid credentials. Please check
            the provided credentials and try again.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since this resource cannot be accessed by
            the provided credentials.
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The resource is in an incompatible state.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - OAuth2:
        - bmc
      summary: Delete a Public Network.
      tags:
      - Public Networks
    get:
      description: Retrieve Public Network Details.
      operationId: publicNetworksNetworkIdGet
      parameters:
      - description: The Public Network identifier.
        example: 603f3b2cfcaf050643b89a4b
        explode: false
        in: path
        name: publicNetworkId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                PublicNetworkWithOnlyRequiredFields:
                  value:
                    id: 60472f76bbadb4f36541d2fd
                    name: Initial public network
                    location: PHX
                    ipBlocks: []
                    vlanId: 10
                    status: READY
                    createdOn: 2022-04-05T13:50:30.491Z
                    memberships: []
                PublicNetworkOnlyWithoutIpBlocks:
                  value:
                    id: 60472f76bbadb4f36541d2fd
                    name: Initial public network
                    location: PHX
                    description: "My first public network #1"
                    ipBlocks: []
                    vlanId: 10
                    status: READY
                    createdOn: 2022-04-05T13:50:30.491Z
                    memberships: []
                PublicNetworkWithIpBlocks:
                  value:
                    id: 60472f76bbadb4f36541d2fd
                    name: Initial public network
                    location: PHX
                    description: "My first public network #1"
                    ipBlocks:
                    - id: 60473a6115e34466c9f8f083
                    - id: 616e6ec6d66b406a45ab8797
                    - id: 617d2d128bacbb05aca2caeb
                    - id: 617d2da78bacbb05aca2caef
                    - id: 618e5383a835704f8c59522d
                    - id: 617d2f834dcf2869f8e4ef0b
                    - id: 5f325c71b8a7ef1473e3c85b
                    - id: 5ff5cc9bc1acf144d9106233
                    - id: 610001e7da283e36d0a0df9f
                    - id: 613b51c01f4b04615ba1d3be
                    vlanId: 10
                    status: READY
                    createdOn: 2022-04-05T13:50:30.491Z
                    memberships: []
                PublicNetworkWithIpBlocksAndServers:
                  value:
                    id: 60472f76bbadb4f36541d2fd
                    name: Initial public network
                    location: PHX
                    description: "My first public network #1"
                    ipBlocks:
                    - id: 60473a6115e34466c9f8f083
                    - id: 616e6ec6d66b406a45ab8797
                    - id: 617d2d128bacbb05aca2caeb
                    - id: 617d2da78bacbb05aca2caef
                    - id: 618e5383a835704f8c59522d
                    - id: 617d2f834dcf2869f8e4ef0b
                    - id: 5f325c71b8a7ef1473e3c85b
                    - id: 5ff5cc9bc1acf144d9106233
                    - id: 610001e7da283e36d0a0df9f
                    - id: 613b51c01f4b04615ba1d3be
                    vlanId: 10
                    status: READY
                    createdOn: 2022-04-05T13:50:30.491Z
                    memberships:
                    - resourceId: 6128d3754b478b76ee8b3cdd
                      resourceType: server
                      ips:
                      - 10.111.14.123
                    - resourceId: 5feae6b0b00bfb14eda82fc7
                      resourceType: server
                      ips:
                      - 10.111.14.200
                      - 10.111.14.201
                      - 10.111.14.202
              schema:
                $ref: '#/components/schemas/PublicNetwork'
          description: Public Network Details.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to invalid credentials. Please check
            the provided credentials and try again.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since this resource cannot be accessed by
            the provided credentials.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - OAuth2:
        - bmc.read
      summary: Get a Public Network.
      tags:
      - Public Networks
    patch:
      description: Update Public Network's Details.
      operationId: publicNetworksNetworkIdPatch
      parameters:
      - description: The Public Network identifier.
        example: 603f3b2cfcaf050643b89a4b
        explode: false
        in: path
        name: publicNetworkId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            examples:
              PublicNetworkModifyWithNameAndDescription:
                value:
                  name: My public network
                  description: The new description of my public network
              PublicNetworkModifyWithNameOnly:
                value:
                  name: My public network
              PublicNetworkModifyWithDescriptionOnly:
                value:
                  description: The new description of my public network
            schema:
              $ref: '#/components/schemas/PublicNetworkModify'
      responses:
        "200":
          content:
            application/json:
              example:
                id: 60472f76bbadb4f36541d2fd
                name: My public network
                location: PHX
                description: The new description of my public network
                ipBlocks: []
                vlanId: 10
                status: READY
                createdOn: 2022-04-05T13:50:30.491Z
                memberships: []
              schema:
                $ref: '#/components/schemas/PublicNetwork'
          description: Network successfully updated.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to wrong data. Please check the provided
            parameters and try again.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to invalid credentials. Please check
            the provided credentials and try again.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since this resource cannot be accessed by
            the provided credentials.
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The resource is in an incompatible state.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - OAuth2:
        - bmc
      summary: Update Public Network's Details.
      tags:
      - Public Networks
  /public-networks/{publicNetworkId}/ip-blocks:
    post:
      description: Adds an IP block to this public network.
      operationId: publicNetworksNetworkIdIpBlocksPost
      parameters:
      - description: The Public Network identifier.
        example: 603f3b2cfcaf050643b89a4b
        explode: false
        in: path
        name: publicNetworkId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            example:
              id: 60473a6115e34466c9f8f083
            schema:
              $ref: '#/components/schemas/PublicNetworkIpBlock'
      responses:
        "202":
          content:
            application/json:
              example:
                id: 60473a6115e34466c9f8f083
              schema:
                $ref: '#/components/schemas/PublicNetworkIpBlock'
          description: The specified IP block is being added to the public network.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to wrong data. Please check the provided
            parameters and try again.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to invalid credentials. Please check
            the provided credentials and try again.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since this resource cannot be accessed by
            the provided credentials.
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The resource is in an incompatible state.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - OAuth2:
        - bmc
      summary: Adds an IP block to this public network.
      tags:
      - Public Networks
  /public-networks/{publicNetworkId}/ip-blocks/{ipBlockId}:
    delete:
      description: Removes the IP Block from the Public Network. The result of this
        is that any traffic addressed to any IP within the block will not be routed
        to this network anymore. Please ensure that no resource members within this
        network have any IPs assigned from the IP Block being removed.
      operationId: publicNetworksNetworkIdIpBlocksIpBlockIdDelete
      parameters:
      - description: The Public Network identifier.
        example: 603f3b2cfcaf050643b89a4b
        explode: false
        in: path
        name: publicNetworkId
        required: true
        schema:
          type: string
        style: simple
      - description: The IP Block identifier.
        example: 6047127fed34ecc3ba8402d2
        explode: false
        in: path
        name: ipBlockId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "202":
          content:
            application/json:
              example: The specified IP block is being removed from the Public Network.
              schema:
                description: The specified IP block is being removed from the Public
                  Network.
                example: The specified IP block is being removed from the Public Network.
                type: string
          description: The specified IP block is being removed from the Public Network.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to wrong data. Please check the provided
            parameters and try again.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to invalid credentials. Please check
            the provided credentials and try again.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since this resource cannot be accessed by
            the provided credentials.
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The resource is in an incompatible state.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - OAuth2:
        - bmc
      summary: Removes the IP Block from the Public Network.
      tags:
      - Public Networks
components:
  parameters:
    privateNetworkIdPathParam:
      description: The private network identifier.
      example: 603f3b2cfcaf050643b89a4b
      explode: false
      in: path
      name: privateNetworkId
      required: true
      schema:
        type: string
      style: simple
    publicNetworkIdPathParam:
      description: The Public Network identifier.
      example: 603f3b2cfcaf050643b89a4b
      explode: false
      in: path
      name: publicNetworkId
      required: true
      schema:
        type: string
      style: simple
    ipBlockIdPathParam:
      description: The IP Block identifier.
      example: 6047127fed34ecc3ba8402d2
      explode: false
      in: path
      name: ipBlockId
      required: true
      schema:
        type: string
      style: simple
  responses:
    BadRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The request failed due to wrong data. Please check the provided
        parameters and try again.
    Unauthorized:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The request failed due to invalid credentials. Please check the
        provided credentials and try again.
    Forbidden:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The request failed since this resource cannot be accessed by the
        provided credentials.
    InternalServerError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The server encountered an unexpected condition that prevented it
        from fulfilling the request.
    NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The request failed since the resource could not been found.
    Conflict:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The resource is in an incompatible state.
  schemas:
    PrivateNetwork:
      description: Private Network details.
      example:
        servers:
        - id: 603f3e995c18d515cda9c4f8
          ips:
          - 10.0.0.2
          - 10.0.0.3
        - id: 603f3e995c18d515cda9c4f8
          ips:
          - 10.0.0.2
          - 10.0.0.3
        vlanId: 10
        name: Sample Network
        description: Further details on the network
        location: PHX
        cidr: 10.0.0.0/24
        id: 604721852cf65253d151528b
        type: PRIVATE
        locationDefault: true
        createdOn: 2022-04-07T13:30:30.491Z
        memberships:
        - resourceId: 603f3e995c18d515cda9c4f8
          ips:
          - 10.111.14.104
          - 10.111.14.105
          - 10.111.14.106
          resourceType: server
        - resourceId: 603f3e995c18d515cda9c4f8
          ips:
          - 10.111.14.104
          - 10.111.14.105
          - 10.111.14.106
          resourceType: server
        status: READY
      properties:
        id:
          description: The private network identifier.
          example: 604721852cf65253d151528b
          type: string
        name:
          description: The friendly name of this private network.
          example: Sample Network
          maxLength: 100
          minLength: 1
          type: string
        description:
          description: The description of this private network.
          example: Further details on the network
          maxLength: 250
          type: string
        vlanId:
          description: The VLAN of this private network.
          example: 10
          type: integer
        type:
          description: The type of the private network.
          example: PRIVATE
          type: string
        location:
          description: The location of this private network.
          example: PHX
          type: string
        locationDefault:
          description: Identifies network as the default private network for the specified
            location.
          example: true
          type: boolean
        cidr:
          description: IP range associated with this private network in CIDR notation.
          example: 10.0.0.0/24
          type: string
        servers:
          deprecated: true
          items:
            $ref: '#/components/schemas/PrivateNetworkServer'
          type: array
        memberships:
          description: A list of resources that are members of this private network.
          items:
            $ref: '#/components/schemas/NetworkMembership'
          type: array
        status:
          description: "The status of the private network. Can have one of the following\
            \ values: `BUSY` or `READY`."
          example: READY
          type: string
        createdOn:
          description: Date and time when this private network was created.
          example: 2022-04-07T13:30:30.491Z
          format: date-time
          type: string
      required:
      - cidr
      - createdOn
      - id
      - location
      - locationDefault
      - memberships
      - name
      - servers
      - status
      - type
      - vlanId
      type: object
    PrivateNetworkServer:
      description: Server details linked to the Private Network.
      example:
        id: 603f3e995c18d515cda9c4f8
        ips:
        - 10.0.0.2
        - 10.0.0.3
      properties:
        id:
          description: The server identifier.
          example: 603f3e995c18d515cda9c4f8
          type: string
        ips:
          description: List of private IPs associated to the server.
          example:
          - 10.0.0.2
          - 10.0.0.3
          items:
            example: 10.0.0.2
            type: string
          type: array
      required:
      - id
      - ips
      type: object
    PrivateNetworkCreate:
      description: Details of Private Network to be created.
      example:
        vlanId: 10
        name: Sample Network
        description: Further details on the network
        location: PHX
        cidr: 10.0.0.0/24
        locationDefault: true
      properties:
        name:
          description: The friendly name of this private network. This name should
            be unique.
          example: Sample Network
          maxLength: 100
          minLength: 1
          type: string
        description:
          description: The description of this private network.
          example: Further details on the network
          maxLength: 250
          type: string
        location:
          description: "The location of this private network. Supported values are\
            \ `PHX`, `ASH`, `SGP`, `NLD`, `CHI`, `SEA` and `AUS`."
          example: PHX
          type: string
        locationDefault:
          default: false
          description: Identifies network as the default private network for the specified
            location.
          example: true
          type: boolean
        vlanId:
          description: The VLAN that will be assigned to this network.
          example: 10
          maximum: 4094
          minimum: 2
          type: integer
        cidr:
          description: IP range associated with this private network in CIDR notation.
          example: 10.0.0.0/24
          type: string
      required:
      - cidr
      - location
      - name
      type: object
    PrivateNetworkModify:
      description: Object including details to be modified in the Private Network.
      example:
        name: Sample network
        description: Further details on the network.
        locationDefault: true
      properties:
        name:
          description: A friendly name given to the private network. This name should
            be unique.
          example: Sample network
          maxLength: 100
          minLength: 1
          type: string
        description:
          description: A description of this private network
          example: Further details on the network.
          maxLength: 250
          type: string
        locationDefault:
          description: Identifies network as the default private network for the specified
            location.
          example: true
          type: boolean
      required:
      - locationDefault
      - name
      type: object
    PublicNetwork:
      description: Public Network details.
      example:
        vlanId: 10
        ipBlocks:
        - id: 60473a6115e34466c9f8f083
        - id: 60473a6115e34466c9f8f083
        name: Sample Network
        description: Further details on the network.
        location: PHX
        id: 604721852cf65253d151528b
        createdOn: 2022-04-05T13:50:30.491Z
        memberships:
        - resourceId: 603f3e995c18d515cda9c4f8
          ips:
          - 10.111.14.104
          - 10.111.14.105
          - 10.111.14.106
          resourceType: server
        - resourceId: 603f3e995c18d515cda9c4f8
          ips:
          - 10.111.14.104
          - 10.111.14.105
          - 10.111.14.106
          resourceType: server
        status: READY
      properties:
        id:
          description: The public network identifier.
          example: 604721852cf65253d151528b
          type: string
        vlanId:
          description: The VLAN of this public network.
          example: 10
          type: integer
        memberships:
          description: A list of resources that are members of this public network.
          items:
            $ref: '#/components/schemas/NetworkMembership'
          type: array
        name:
          description: The friendly name of this public network.
          example: Sample Network
          maxLength: 100
          minLength: 1
          type: string
        location:
          description: "The location of this public network. Supported values are\
            \ `PHX`, `ASH`, `SGP`, `NLD`, `CHI`, `SEA` and `AUS`."
          example: PHX
          type: string
        description:
          description: The description of this public network.
          example: Further details on the network.
          maxLength: 250
          type: string
        status:
          description: "The status of the public network. Can have one of the following\
            \ values: `BUSY` or `READY`."
          example: READY
          type: string
        createdOn:
          description: Date and time when this public network was created.
          example: 2022-04-05T13:50:30.491Z
          format: date-time
          type: string
        ipBlocks:
          description: A list of IP Blocks that are associated with this public network.
          items:
            $ref: '#/components/schemas/PublicNetworkIpBlock'
          type: array
      required:
      - createdOn
      - id
      - ipBlocks
      - location
      - memberships
      - name
      - status
      - vlanId
      type: object
    PublicNetworkIpBlock:
      description: The assigned IP block to the Public Network.
      example:
        id: 60473a6115e34466c9f8f083
      properties:
        id:
          description: The IP Block identifier.
          example: 60473a6115e34466c9f8f083
          type: string
      required:
      - id
      type: object
    PublicNetworkCreate:
      description: Details of Public Network to be created.
      example:
        vlanId: 10
        ipBlocks:
        - id: 60473a6115e34466c9f8f083
        - id: 60473a6115e34466c9f8f083
        - id: 60473a6115e34466c9f8f083
        - id: 60473a6115e34466c9f8f083
        - id: 60473a6115e34466c9f8f083
        name: Sample Network
        description: Further details on the network.
        location: PHX
      properties:
        name:
          description: The friendly name of this public network. This name should
            be unique.
          example: Sample Network
          maxLength: 100
          minLength: 1
          type: string
        description:
          description: The description of this public network.
          example: Further details on the network.
          maxLength: 250
          type: string
        location:
          description: "The location of this public network. Supported values are\
            \ `PHX`, `ASH`, `SGP`, `NLD`, `CHI`, `SEA` and `AUS`."
          example: PHX
          type: string
        vlanId:
          description: The VLAN that will be assigned to this network.
          example: 10
          maximum: 4094
          minimum: 2
          type: integer
        ipBlocks:
          description: A list of IP Blocks that will be associated with this public
            network.
          items:
            $ref: '#/components/schemas/PublicNetworkIpBlock'
          maxItems: 10
          type: array
      required:
      - location
      - name
      type: object
    PublicNetworkModify:
      description: Public Network Modifiable Details.
      example:
        name: Sample Network
        description: Further details on the network.
      properties:
        name:
          description: A friendly name given to the network. This name should be unique.
          example: Sample Network
          maxLength: 100
          minLength: 1
          type: string
        description:
          description: The description of this public network
          example: Further details on the network.
          maxLength: 250
          type: string
      type: object
    NetworkMembership:
      description: Resource details linked to the Network.
      example:
        resourceId: 603f3e995c18d515cda9c4f8
        ips:
        - 10.111.14.104
        - 10.111.14.105
        - 10.111.14.106
        resourceType: server
      properties:
        resourceId:
          description: The resource identifier.
          example: 603f3e995c18d515cda9c4f8
          type: string
        resourceType:
          description: The resource's type.
          example: server
          type: string
        ips:
          description: List of IPs associated to the resource.
          example:
          - 10.111.14.104
          - 10.111.14.105
          - 10.111.14.106
          items:
            type: string
          type: array
      required:
      - ips
      - resourceId
      - resourceType
      type: object
    Error:
      properties:
        message:
          description: The description detailing the cause of the error code.
          readOnly: true
          type: string
        validationErrors:
          description: "Validation errors, if any."
          items:
            type: string
          readOnly: true
          type: array
      required:
      - message
      type: object
  securitySchemes:
    OAuth2:
      flows:
        clientCredentials:
          scopes:
            bmc: Grants full access to bmc-api.
            bmc.read: Grants read only access to bmc-api.
          tokenUrl: https://auth.phoenixnap.com/auth/realms/BMC/protocol/openid-connect/token
      type: oauth2
