openapi: 3.0.2
info:
  title: Network Storage API
  description: |
    Create, list, edit, and delete storage networks with the Network Storage API. Use storage networks to expand storage capacity on a private network.
    <br>
    <span class='pnap-api-knowledge-base-link'>
    Knowledge base articles to help you can be found
    <a href='https://phoenixnap.com/kb/bare-metal-cloud-storage' target='_blank'>here</a>
    </span>
    <br>
    <b>All URLs are relative to (https://api.phoenixnap.com/network-storage/v1/)</b>
  termsOfService: https://phoenixnap.com/infrastructure-solutions/legal-it/privacy-shield-compliant-privacy-policy
  version: '1.0'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: PhoenixNAP Team
    email: support@phoenixnap.com
    url: https://phoenixnap.com/
servers:
  - url: https://api.phoenixnap.com/network-storage/v1
security:
  - OAuth2:
      - networkstorage
      - networkstorage.read
tags:
  - name: Storage Networks
    description: Storage Networks operations.
paths:
  /storage-networks:
    get:
      parameters:
        - in: query
          name: location
          required: false
          description: If present will filter the result by the given location.
          schema:
            description: Supported values are `PHX` and `ASH`.
            type: string
          example: PHX
      tags:
        - Storage Networks
      description: List all storage networks.
      summary: List all storage networks.
      operationId: storageNetworksGet
      security:
        - OAuth2:
            - networkstorage.read
      responses:
        '200':
          description: List all storage networks.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StorageNetwork'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - Storage Networks
      description: Create a storage network and volume.
      summary: Create a storage network and volume.
      operationId: storageNetworksPost
      security:
        - OAuth2:
            - networkstorage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StorageNetworkCreate'
      responses:
        '202':
          description: Accepted request for creating a Storage network.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StorageNetwork'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /storage-networks/{storageId}:
    parameters:
      - $ref: '#/components/parameters/storageIdParam'
    get:
      tags:
        - Storage Networks
      description: Get storage network details.
      summary: Get storage network details.
      operationId: storageNetworksIdGet
      security:
        - OAuth2:
            - networkstorage.read
      responses:
        '200':
          description: Get storage network details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StorageNetwork'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
    patch:
      tags:
        - Storage Networks
      description: Update storage network details.
      summary: Update storage network details.
      operationId: storageNetworksIdPatch
      security:
        - OAuth2:
            - networkstorage
      requestBody:
        required: true
        description: Storage network to be updated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StorageNetworkUpdate'
            example:
              name: My storage network
              description: Storage network description
      responses:
        '200':
          description: Updated storage network.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StorageNetwork'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - Storage Networks
      description: Delete a storage network and its volume. A storage network can only be removed if it's not in 'BUSY' state. Billing stops on storage network deletion.
      summary: Delete a storage network and its volume.
      operationId: storageNetworksIdDelete
      security:
        - OAuth2:
            - networkstorage
      responses:
        '204':
          description: Initiate the deletion process for the specified Storage Network.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /storage-networks/{storageId}/volumes:
    parameters:
      - $ref: '#/components/parameters/storageIdParam'
    get:
      parameters:
        - in: query
          name: tag
          schema:
            type: array
            items:
              type: string
          description: A list of query parameters related to tags in the form of tagName.tagValue
          example: env.dev
      tags:
        - Storage Networks
      description: Display one or more volumes belonging to a storage network.
      summary: Display one or more volumes belonging to a storage network.
      operationId: storageNetworksStorageNetworkIdVolumesGet
      security:
        - OAuth2:
            - networkstorage.read
      responses:
        '200':
          description: Get a storage network's volume details.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Volume'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - Storage Networks
      description: Create a volume belonging to a storage network.
      summary: Create a volume belonging to a storage network.
      operationId: storageNetworksStorageNetworkIdVolumesPost
      security:
        - OAuth2:
            - networkstorage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VolumeCreate'
      responses:
        '202':
          description: Volume that is being created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Volume'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /storage-networks/{storageId}/volumes/{volumeId}:
    parameters:
      - $ref: '#/components/parameters/storageIdParam'
      - $ref: '#/components/parameters/volumeIdParam'
    get:
      tags:
        - Storage Networks
      description: Get a storage network's volume details.
      summary: Get a storage network's volume details.
      operationId: storageNetworksStorageNetworkIdVolumesVolumeIdGet
      security:
        - OAuth2:
            - networkstorage.read
      responses:
        '200':
          description: Get a storage network's volume details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Volume'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
    patch:
      tags:
        - Storage Networks
      description: Update a storage network's volume details. Volume's capacity requested cannot be less than or equal to current volume's capacity.
      summary: Update a storage network's volume details.
      operationId: storageNetworksStorageNetworkIdVolumesVolumeIdPatch
      security:
        - OAuth2:
            - networkstorage
      requestBody:
        required: true
        description: Storage network volume to be updated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VolumeUpdate'
      responses:
        '200':
          description: Updated volume details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Volume'
        '202':
          description: Updating volume details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Volume'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
    delete:
      tags:
        - Storage Networks
      description: Delete a Storage Network's Volume
      summary: Delete a Storage Network's Volume
      operationId: storageNetworksStorageNetworkIdVolumesVolumeIdDelete
      security:
        - OAuth2:
            - networkstorage
      responses:
        '204':
          description: Initiate the deletion process for the specified Volume.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /storage-networks/{storageId}/volumes/{volumeId}/tags:
    parameters:
      - $ref: '#/components/parameters/storageIdParam'
      - $ref: '#/components/parameters/volumeIdParam'
    put:
      tags:
        - Storage Networks
      description: Overwrites tags assigned for the volume.
      summary: Overwrites tags assigned for the volume.
      operationId: storageNetworksStorageNetworkIdVolumesVolumeIdTagsPut
      security:
        - OAuth2:
            - networkstorage
      requestBody:
        required: true
        description: Tags to assign to the volume.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TagAssignmentRequest'
      responses:
        '200':
          description: Volume tags set.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Volume'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.phoenixnap.com/auth/realms/BMC/protocol/openid-connect/token
          scopes:
            networkstorage: Grants full access to Network Storage API.
            networkstorage.read: Grants read only access to Network Storage API.
  schemas:
    StorageNetwork:
      type: object
      description: Storage network.
      properties:
        id:
          description: Storage network ID.
          type: string
          example: 603f3b2cfcaf050643b89a4b
        name:
          description: Storage network friendly name.
          type: string
          example: My storage network
        description:
          description: Storage network description.
          type: string
          example: My storage network description
        status:
          $ref: '#/components/schemas/Status'
        location:
          description: Location of storage network. Currently this field should be set to `PHX` or `ASH`.
          type: string
          example: PHX
        networkId:
          description: Id of network the storage belongs to.
          type: string
          example: 603f3b2cfcaf050643b89a4b
        ips:
          description: IP of the storage network.
          type: array
          items:
            type: string
          example:
            - 100.64.0.1
            - 100.64.0.2
        createdOn:
          description: Date and time when this storage network was created.
          type: string
          format: date-time
          example: '2021-03-13T20:24:32.491Z'
        deleteRequestedOn:
          description: Date and time of the initial request for storage network deletion.
          type: string
          format: date-time
          example: '2022-04-07T08:50:20.359Z'
        volumes:
          description: Volume for a storage network.
          type: array
          items:
            $ref: '#/components/schemas/Volume'
    StorageNetworkCreate:
      type: object
      description: Create Storage Network.
      required:
        - name
        - location
        - volumes
      properties:
        name:
          description: Storage network friendly name.
          type: string
          minLength: 1
          maxLength: 100
          example: My storage network
          pattern: ^(?=.*[a-zA-Z])([a-zA-Z0-9(). -])+$
        description:
          description: Storage network description.
          type: string
          maxLength: 250
          example: My storage network description
        location:
          description: Location of storage network. Currently this field should be set to `PHX` or `ASH`.
          type: string
          example: PHX
        volumes:
          description: Volume to be created alongside storage. Currently only 1 volume is supported.
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/StorageNetworkVolumeCreate'
        clientVlan:
          description: Custom Client VLAN that the Storage Network will be set to.
          type: integer
          minimum: 2
          maximum: 4094
    StorageNetworkVolumeCreate:
      title: StorageNetworkVolumeCreate
      type: object
      description: Create Volume.
      required:
        - name
        - capacityInGb
      properties:
        name:
          description: Volume friendly name.
          type: string
          minLength: 1
          maxLength: 100
          example: My volume name
          pattern: ^(?=.*[a-zA-Z])([a-zA-Z0-9(). -])+$
        description:
          description: Volume description.
          type: string
          maxLength: 250
          example: My volume description
        pathSuffix:
          description: Last part of volume's path.
          type: string
          minLength: 0
          maxLength: 27
          pattern: ^(\/[\w-]+)+$|^$
          example: /shared-docs
        capacityInGb:
          description: Capacity of Volume in GB. Currently only whole numbers and multiples of 1000GB are supported.
          type: integer
          minimum: 1000
          example: 2000
        tags:
          description: Tags to set to the resource. To create a new tag or list all the existing tags that you can use, refer to [Tags API](https://developers.phoenixnap.com/docs/tags/1/overview).
          type: array
          items:
            $ref: '#/components/schemas/TagAssignmentRequest'
          example:
            - name: stage
              value: beta
            - name: group
              value: discounted
    StorageNetworkUpdate:
      type: object
      description: Update storage network.
      properties:
        name:
          description: Storage network friendly name.
          type: string
          minLength: 1
          maxLength: 100
          example: My storage network
          pattern: ^(?=.*[a-zA-Z])([a-zA-Z0-9(). -])+$
        description:
          description: Storage network description.
          type: string
          maxLength: 250
          example: My storage network description
    Volume:
      type: object
      description: Volume for a storage network.
      properties:
        id:
          description: Volume ID.
          type: string
          example: 50dc434c-9bba-427b-bcd6-0bdba45c4dd2
        name:
          description: Volume friendly name.
          type: string
          example: My volume name
        description:
          description: Volume description.
          type: string
          example: My volume description
        path:
          description: Volume's full path. It is in form of `/{volumeId}/pathSuffix`'.
          type: string
          example: /qjul77ahf5fplr2ba484/shared-docs
        pathSuffix:
          description: Last part of volume's path.
          type: string
          example: /shared-docs
        capacityInGb:
          description: Maximum capacity in GB.
          type: integer
          example: 2000
        usedCapacityInGb:
          description: Used capacity in GB, updated periodically.
          type: integer
          example: 1000
        protocol:
          description: File system protocol. Currently this field should be set to `NFS`.
          type: string
          example: NFS
        status:
          $ref: '#/components/schemas/Status'
        createdOn:
          type: string
          format: date-time
          example: '2021-03-13T20:24:32.491Z'
        deleteRequestedOn:
          description: Date and time of the initial request for volume deletion.
          type: string
          format: date-time
          example: '2022-04-07T08:50:20.359Z'
        permissions:
          $ref: '#/components/schemas/Permissions'
        tags:
          description: The tags assigned if any.
          type: array
          items:
            $ref: '#/components/schemas/TagAssignment'
          example:
            - name: stage
              value: beta
            - name: group
              value: discounted
    VolumeCreate:
      title: VolumeCreate
      type: object
      description: Create Volume.
      required:
        - name
        - capacityInGb
      properties:
        name:
          description: Volume friendly name.
          type: string
          minLength: 1
          maxLength: 100
          example: My volume name
          pattern: ^(?=.*[a-zA-Z])([a-zA-Z0-9(). -])+$
        description:
          description: Volume description.
          type: string
          maxLength: 250
          example: My volume description
        pathSuffix:
          description: Last part of volume's path.
          type: string
          minLength: 0
          maxLength: 27
          pattern: ^(\/[\w-]+)+$|^$
          example: /shared-docs
        capacityInGb:
          description: Capacity of Volume in GB. Currently only whole numbers and multiples of 1000GB are supported.
          type: integer
          minimum: 1000
          example: 2000
        permissions:
          $ref: '#/components/schemas/PermissionsCreate'
        tags:
          description: Tags to set to the resource. To create a new tag or list all the existing tags that you can use, refer to [Tags API](https://developers.phoenixnap.com/docs/tags/1/overview).
          type: array
          items:
            $ref: '#/components/schemas/TagAssignmentRequest'
          example:
            - name: stage
              value: beta
            - name: group
              value: discounted
    VolumeUpdate:
      type: object
      description: Update storage network volume.
      properties:
        name:
          description: Volume friendly name.
          type: string
          minLength: 1
          maxLength: 100
          example: New Volume name
          pattern: ^(?=.*[a-zA-Z])([a-zA-Z0-9(). -])+$
        description:
          description: Volume description.
          type: string
          maxLength: 250
          example: New Volume description
        capacityInGb:
          description: Capacity of Volume in GB. Currently only whole numbers and multiples of 1000GB are supported.
          type: integer
          minimum: 2000
          example: 2000
        pathSuffix:
          description: Last part of volume's path.
          type: string
          minLength: 0
          maxLength: 27
          pattern: ^(\/[\w-]+)+$|^$
        permissions:
          $ref: '#/components/schemas/PermissionsUpdate'
    Permissions:
      type: object
      description: Permissions for a volume.
      properties:
        nfs:
          $ref: '#/components/schemas/NfsPermissions'
    PermissionsCreate:
      type: object
      description: Update permissions for a volume.
      properties:
        nfs:
          $ref: '#/components/schemas/NfsPermissionsCreate'
    PermissionsUpdate:
      type: object
      description: Update permissions for a volume.
      properties:
        nfs:
          $ref: '#/components/schemas/NfsPermissionsUpdate'
    NfsPermissions:
      type: object
      description: NFS specific permissions on a volume.
      properties:
        readWrite:
          description: Read/Write access.
          type: array
          items:
            type: string
            example: 100.80.0.5
          example:
            - 100.80.0.5
            - 100.80.0.6
        readOnly:
          description: Read only access.
          type: array
          items:
            type: string
            example: 100.80.0.5
          example:
            - 100.80.0.5
        rootSquash:
          description: Root squash permission.
          type: array
          items:
            type: string
            example: 100.80.0.5/24
          example:
            - 100.80.0.5
            - 100.80.0.4/24
        noSquash:
          description: No squash permission.
          type: array
          items:
            type: string
            example: 100.80.0.*
          example:
            - 100.80.0.7
            - 100.80.0.*
        allSquash:
          description: All squash permission.
          type: array
          items:
            type: string
            example: 100.80.0.5
          example:
            - 100.80.0.5
            - 100.80.0.6
    NfsPermissionsCreate:
      type: object
      description: NFS specific permissions on a volume.
      properties:
        readWrite:
          description: Read/Write access.
          type: array
          items:
            type: string
            pattern: ^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}(\/(3[0-2]|[1-2]\d|[1-9]))?$|^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.){0,3}\*$
            example: 100.80.0.5
          example:
            - 100.80.0.5
            - 100.80.0.6
        readOnly:
          description: Read only access.
          type: array
          items:
            type: string
            pattern: ^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}(\/(3[0-2]|[1-2]\d|[1-9]))?$|^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.){0,3}\*$
            example: 100.80.0.5
          example:
            - 100.80.0.5
        rootSquash:
          description: Root squash permission.
          type: array
          items:
            type: string
            pattern: ^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}(\/(3[0-2]|[1-2]\d|[1-9]))?$|^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.){0,3}\*$
            example: 100.80.0.5/24
          example:
            - 100.80.0.5
            - 100.80.0.4/24
        noSquash:
          description: No squash permission.
          type: array
          items:
            type: string
            pattern: ^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}(\/(3[0-2]|[1-2]\d|[1-9]))?$|^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.){0,3}\*$
            example: 100.80.0.*
          example:
            - 100.80.0.7
            - 100.80.0.*
        allSquash:
          description: All squash permission.
          type: array
          items:
            type: string
            pattern: ^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}(\/(3[0-2]|[1-2]\d|[1-9]))?$|^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.){0,3}\*$
            example: 100.80.0.5
          example:
            - 100.80.0.5
            - 100.80.0.6
    NfsPermissionsUpdate:
      type: object
      description: Update NFS specific permissions on a volume.
      properties:
        readWrite:
          description: Read/Write access.
          type: array
          items:
            type: string
            pattern: ^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}(\/(3[0-2]|[1-2]\d|[1-9]))?$|^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.){0,3}\*$
            example: 100.80.0.5
          example:
            - 100.80.0.5
            - 100.80.0.6
        readOnly:
          description: Read only access.
          type: array
          items:
            type: string
            pattern: ^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}(\/(3[0-2]|[1-2]\d|[1-9]))?$|^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.){0,3}\*$
            example: 100.80.0.5
          example:
            - 100.80.0.5
        rootSquash:
          description: Root squash permission.
          type: array
          items:
            type: string
            pattern: ^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}(\/(3[0-2]|[1-2]\d|[1-9]))?$|^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.){0,3}\*$
            example: 100.80.0.5/24
          example:
            - 100.80.0.5
            - 100.80.0.4/24
        noSquash:
          description: No squash permission.
          type: array
          items:
            type: string
            pattern: ^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}(\/(3[0-2]|[1-2]\d|[1-9]))?$|^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.){0,3}\*$
            example: 100.80.0.*
          example:
            - 100.80.0.7
            - 100.80.0.*
        allSquash:
          description: All squash permission.
          type: array
          items:
            type: string
            pattern: ^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}(\/(3[0-2]|[1-2]\d|[1-9]))?$|^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.){0,3}\*$
            example: 100.80.0.5
          example:
            - 100.80.0.5
            - 100.80.0.6
    Status:
      description: Status of the resource. Currently this field should be set to `READY`, `BUSY`, `DELETING` or `ERROR`.
      type: string
      enum:
        - READY
        - BUSY
        - DELETING
        - ERROR
      example: READY
    TagAssignment:
      type: object
      description: Tag assigned to resource.
      required:
        - id
        - name
        - isBillingTag
      properties:
        id:
          description: The unique id of the tag.
          type: string
          example: 60ffafcdffb8b074c7968dad
        name:
          description: The name of the tag.
          type: string
          example: Environment
        value:
          description: The value of the tag assigned to the resource.
          type: string
          example: PROD
        isBillingTag:
          description: Whether or not to show the tag as part of billing and invoices
          type: boolean
          example: true
        createdBy:
          description: Who the tag was created by.
          type: string
          enum:
            - USER
            - SYSTEM
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          readOnly: true
          description: The description detailing the cause of the error code.
        validationErrors:
          type: array
          items:
            type: string
          readOnly: true
          description: Validation errors, if any.
    TagAssignmentRequest:
      type: object
      description: Tag request to assign to resource.
      required:
        - name
      properties:
        name:
          description: 'The name of the tag. Tag names are case-sensitive, and should be composed of a maximum of 100 characters including UTF-8 Unicode letters, numbers, and the following symbols: ''-'', ''_''. Regex: [A-zÀ-ú0-9_-]{1,100}.'
          type: string
          example: Environment
        value:
          description: 'The value of the tag assigned to the resource. Tag values are case-sensitive, and should be composed of a maximum of 100 characters including UTF-8 Unicode letters, numbers, and the following symbols: ''-'', ''_''. Regex: [A-zÀ-ú0-9_-]{1,100}.'
          type: string
          example: PROD
  responses:
    BadRequest:
      description: The request failed due to wrong data. Please check the provided parameters and try again.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: The request failed due to invalid credentials. Please check the provided credentials and try again.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: The request failed since this resource cannot be accessed by the provided credentials.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: The server encountered an unexpected condition that prevented it from fulfilling the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict:
      description: The resource is in an incompatible state.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ServiceUnavailable:
      description: The request failed because service is currently unavailable. Please try again later.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  parameters:
    storageIdParam:
      in: path
      name: storageId
      required: true
      schema:
        type: string
      description: ID of the storage.
      example: 50dc434c-9bba-427b-bcd6-0bdba45c4dd2
    volumeIdParam:
      in: path
      name: volumeId
      required: true
      schema:
        type: string
      description: ID of volume.
      example: 50dc434c-9bba-427b-bcd6-0bdba45c4dd2
