openapi: 3.0.2
info:
  title: Networks API
  description: |
    Create, list, edit and delete public/private networks with the Network API. Use public networks to place multiple 
    servers on the same network or VLAN. Assign new servers with IP addresses from the same CIDR range. Use private 
    networks to avoid unnecessary egress data charges. Model your networks according to your business needs.<br>
    <br>
    <span class='pnap-api-knowledge-base-link'>
    Helpful knowledge base articles are available for 
    <a href='https://phoenixnap.com/kb/bmc-server-management-via-api#multi-private-backend-network-api' target='_blank'>multi-private backend networks</a>
    and <a href='https://phoenixnap.com/kb/bmc-server-management-via-api#ftoc-heading-15' target='_blank'>public networks</a>.
    </span><br>
    <br>
    <b>All URLs are relative to (https://api.phoenixnap.com/networks/v1/)</b>
  termsOfService: https://phoenixnap.com/infrastructure-solutions/legal-it/privacy-shield-compliant-privacy-policy
  version: '1.0'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: PhoenixNAP Team
    email: support@phoenixnap.com
    url: https://phoenixnap.com/
security:
  - OAuth2:
      - bmc
      - bmc.read
servers:
  - url: https://api.phoenixnap.com/networks/v1
tags:
  - name: Private Networks
    description: Private Network operations
  - name: Public Networks
    description: Public networks operations
paths:
  /private-networks:
    get:
      tags:
        - Private Networks
      description: List all Private Networks owned by account.
      summary: List Private Networks.
      operationId: privateNetworksGet
      security:
        - OAuth2:
            - bmc.read
      parameters:
        - in: query
          name: location
          required: false
          description: If present will filter the result by the given location of the Private Networks.
          schema:
            description: Supported values are `PHX`, `ASH`, `SGP`, `NLD`, `CHI`, `SEA` and `AUS`.
            type: string
          example: PHX
      responses:
        '200':
          description: List of all the Private Networks owned by account.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PrivateNetwork'
              example:
                - id: 604724a5a807f2d3be8660c7
                  name: My Default Backend Network
                  type: PRIVATE
                  location: PHX
                  locationDefault: true
                  vlanId: 10
                  description: My Default Backend Network
                  cidr: 10.0.0.0/24
                  servers:
                    - id: 603f3e995c18d515cda9c4f8
                      ips:
                        - 10.0.0.2
                        - 10.0.0.3
                  memberships:
                    - resourceId: 603f3e995c18d515cda9c4f8
                      resourceType: server
                      ips:
                        - 10.0.0.2
                        - 10.0.0.3
                  status: READY
                  createdOn: '2022-04-07T13:20:30.491Z'
                - id: 604724ac9ed2abd18e9f1cb6
                  name: My Additional Backend Network
                  type: PRIVATE
                  location: PHX
                  locationDefault: false
                  vlanId: 11
                  description: My Additional Backend Network
                  cidr: 10.0.0.0/24
                  servers:
                    - id: 603f3e995c18d515cdvte548
                      ips:
                        - 10.0.0.4
                        - 10.0.0.5
                  memberships:
                    - resourceId: 603f3e995c18d515cdvte548
                      resourceType: server
                      ips:
                        - 10.0.0.4
                        - 10.0.0.5
                  status: READY
                  createdOn: '2022-04-07T13:20:30.491Z'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - Private Networks
      description: Create a Private Network.
      summary: Create a Private Network.
      operationId: privateNetworksPost
      security:
        - OAuth2:
            - bmc
      parameters:
        - $ref: '#/components/parameters/forceQueryParam'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrivateNetworkCreate'
            examples:
              PrivateNetworkCreateDefault:
                value:
                  name: My Default Backend Network
                  location: PHX
                  locationDefault: true
                  description: My Default Backend Network
                  cidr: 10.0.0.0/24
              PrivateNetworkCreateNonDefault:
                value:
                  name: My Additional Backend Network
                  location: PHX
                  locationDefault: false
                  description: My Additional Backend Network
                  cidr: 10.0.0.0/24
      responses:
        '201':
          description: Private Network successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrivateNetwork'
              examples:
                PrivateNetworkDefaultCreated:
                  value:
                    id: 604724a5a807f2d3be8660c7
                    name: My Default Backend Network
                    type: PRIVATE
                    location: PHX
                    locationDefault: true
                    vlanId: 10
                    description: My Default Backend Network
                    cidr: 10.0.0.0/24
                    servers: []
                    memberships: []
                    status: READY
                    createdOn: '2022-04-07T13:20:30.491Z'
                PrivateNetworkNonDefaultCreated:
                  value:
                    id: 604724ac9ed2abd18e9f1cb6
                    name: My Additional Backend Network
                    type: PRIVATE
                    location: PHX
                    locationDefault: false
                    vlanId: 11
                    description: My Additional Backend Network
                    cidr: 10.0.0.0/24
                    servers: []
                    memberships: []
                    status: READY
                    createdOn: '2022-04-07T13:20:30.491Z'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /private-networks/{privateNetworkId}:
    parameters:
      - $ref: '#/components/parameters/privateNetworkIdPathParam'
    get:
      tags:
        - Private Networks
      description: Retrieve Private Network Details.
      summary: Get a Private Network.
      operationId: privateNetworksNetworkIdGet
      security:
        - OAuth2:
            - bmc.read
      responses:
        '200':
          description: Private Network Details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrivateNetwork'
              examples:
                DefaultPrivateNetwork:
                  value:
                    id: 604724a5a807f2d3be8660c7
                    name: My Default Backend Network
                    type: PRIVATE
                    location: PHX
                    locationDefault: true
                    vlanId: 10
                    description: My Default Backend Network
                    cidr: 10.0.0.0/24
                    servers:
                      - id: 603f3e995c18d515cda9c4f8
                        ips:
                          - 10.0.0.2
                          - 10.0.0.3
                    memberships:
                      - resourceId: 603f3e995c18d515cda9c4f8
                        resourceType: server
                        ips:
                          - 10.0.0.2
                          - 10.0.0.3
                    status: READY
                    createdOn: '2022-04-07T13:20:30.491Z'
                AdditionalPrivateNetwork:
                  value:
                    id: 604724ac9ed2abd18e9f1cb6
                    name: My Additional Backend Network
                    type: PRIVATE
                    location: PHX
                    locationDefault: false
                    vlanId: 11
                    description: My Additional Backend Network
                    cidr: 10.0.0.0/24
                    servers:
                      - id: 603f3e995c18d515cdvte548
                        ips:
                          - 10.0.0.4
                          - 10.0.0.5
                    memberships:
                      - resourceId: 603f3e995c18d515cdvte548
                        resourceType: server
                        ips:
                          - 10.0.0.4
                          - 10.0.0.5
                    status: READY
                    createdOn: '2022-04-07T13:20:30.491Z'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      tags:
        - Private Networks
      description: Update Private Network Details.
      summary: Update a Private Network.
      operationId: privateNetworksNetworkIdPut
      security:
        - OAuth2:
            - bmc
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrivateNetworkModify'
            examples:
              PrivateNetworkDefaultUpdate:
                value:
                  name: My Default Backend Network
                  description: My Default Backend Network
                  locationDefault: true
              PrivateNetworkNonDefaultUpdate:
                value:
                  name: My Additional Backend Network
                  description: My Additional Backend Network
                  locationDefault: false
      responses:
        '200':
          description: Private Network successfully updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrivateNetwork'
              examples:
                PrivateNetworkDefaultModified:
                  value:
                    id: 604724a5a807f2d3be8660c7
                    name: My Default Backend Network
                    type: PRIVATE
                    location: PHX
                    locationDefault: true
                    vlanId: 10
                    description: My Default Backend Network
                    cidr: 10.0.0.0/24
                    servers:
                      - id: 603f3e995c18d515cda9c4f8
                        ips:
                          - 10.0.0.2
                          - 10.0.0.3
                    memberships:
                      - resourceId: 603f3e995c18d515cda9c4f8
                        resourceType: server
                        ips:
                          - 10.0.0.2
                          - 10.0.0.3
                    status: READY
                    createdOn: '2022-04-07T13:20:30.491Z'
                PrivateNetworkNonDefaultModified:
                  value:
                    id: 604724ac9ed2abd18e9f1cb6
                    name: My Additional Backend Network
                    type: PRIVATE
                    location: PHX
                    locationDefault: false
                    vlanId: 11
                    description: My Additional Backend Network
                    cidr: 10.0.0.0/24
                    servers:
                      - id: 603f3e995c18d515cdvte548
                        ips:
                          - 10.0.0.4
                          - 10.0.0.5
                    memberships:
                      - resourceId: 603f3e995c18d515cdvte548
                        resourceType: server
                        ips:
                          - 10.0.0.4
                          - 10.0.0.5
                    status: READY
                    createdOn: '2022-04-07T13:20:30.491Z'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - Private Networks
      description: Delete Private Network.
      summary: Delete a Private Network.
      operationId: privateNetworksNetworkIdDelete
      security:
        - OAuth2:
            - bmc
      responses:
        '204':
          description: Private Network deleted.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /public-networks:
    get:
      tags:
        - Public Networks
      description: List all Public Networks owned by account.
      summary: List Public Networks.
      operationId: publicNetworksGet
      security:
        - OAuth2:
            - bmc.read
      parameters:
        - in: query
          name: location
          required: false
          description: If present will filter the result by the given location of the Public Networks.
          schema:
            description: Supported values are `PHX`, `ASH`, `SGP`, `NLD`, `CHI`, `SEA` and `AUS`.
            type: string
          example: PHX
      responses:
        '200':
          description: List of all the Public Networks owned by account.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublicNetwork'
              example:
                - id: 60472f76bbadb4f36541d2fd
                  name: Initial public network
                  location: PHX
                  description: 'My first public network #1'
                  ipBlocks:
                    - id: 60473a6115e34466c9f8f083
                    - id: 616e6ec6d66b406a45ab8797
                    - id: 617d2d128bacbb05aca2caeb
                    - id: 617d2da78bacbb05aca2caef
                    - id: 618e5383a835704f8c59522d
                    - id: 617d2f834dcf2869f8e4ef0b
                    - id: 5f325c71b8a7ef1473e3c85b
                    - id: 5ff5cc9bc1acf144d9106233
                    - id: 610001e7da283e36d0a0df9f
                    - id: 613b51c01f4b04615ba1d3be
                  vlanId: 10
                  createdOn: '2022-04-05T13:50:30.491Z'
                  status: READY
                  memberships:
                    - resourceId: 6128d3754b478b76ee8b3cdd
                      resourceType: server
                      ips:
                        - 10.111.14.110
                        - 10.111.14.115
                        - 10.111.14.136
                    - resourceId: 5feae6b0b00bfb14eda82fc7
                      resourceType: server
                      ips:
                        - 10.111.14.121
                - id: 6123b97643046b5bffb1d7c3
                  name: My additional public network
                  location: PHX
                  description: 'My second public network #2'
                  ipBlocks: []
                  vlanId: 11
                  status: READY
                  createdOn: '2022-04-05T13:50:30.491Z'
                  memberships: []
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - Public Networks
      description: Create a public network.
      summary: Create a public network.
      operationId: publicNetworksPost
      security:
        - OAuth2:
            - bmc
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicNetworkCreate'
            examples:
              PublicNetworkCreationWithOnlyRequiredField:
                value:
                  name: Initial public network
                  location: PHX
              PublicNetworkCreationOnlyWithoutIpBlocks:
                value:
                  name: Initial public network
                  location: PHX
                  description: 'My first public network #1'
              PublicNetworkCreationWithAllParameters:
                value:
                  name: Initial public network
                  location: PHX
                  description: 'My first public network #1'
                  ipBlocks:
                    - id: 60473a6115e34466c9f8f083
                    - id: 616e6ec6d66b406a45ab8797
                    - id: 617d2d128bacbb05aca2caeb
                    - id: 617d2da78bacbb05aca2caef
                    - id: 618e5383a835704f8c59522d
                    - id: 617d2f834dcf2869f8e4ef0b
                    - id: 5f325c71b8a7ef1473e3c85b
                    - id: 5ff5cc9bc1acf144d9106233
                    - id: 610001e7da283e36d0a0df9f
                    - id: 613b51c01f4b04615ba1d3be
      responses:
        '201':
          description: Network successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicNetwork'
              examples:
                PublicNetworkWithOnlyRequiredFields:
                  value:
                    id: 60472f76bbadb4f36541d2fd
                    name: Initial public network
                    location: PHX
                    ipBlocks: []
                    vlanId: 10
                    status: READY
                    createdOn: '2022-04-05T13:50:30.491Z'
                    memberships: []
                PublicNetworkOnlyWithoutIpBlocks:
                  value:
                    id: 60472f76bbadb4f36541d2fd
                    name: Initial public network
                    location: PHX
                    description: 'My first public network #1'
                    ipBlocks: []
                    vlanId: 10
                    status: READY
                    createdOn: '2022-04-05T13:50:30.491Z'
                    memberships: []
                PublicNetworkWithAllParameters:
                  value:
                    id: 60472f76bbadb4f36541d2fd
                    name: Initial public network
                    location: PHX
                    description: 'My first public network #1'
                    ipBlocks:
                      - id: 60473a6115e34466c9f8f083
                      - id: 616e6ec6d66b406a45ab8797
                      - id: 617d2d128bacbb05aca2caeb
                      - id: 617d2da78bacbb05aca2caef
                      - id: 618e5383a835704f8c59522d
                      - id: 617d2f834dcf2869f8e4ef0b
                      - id: 5f325c71b8a7ef1473e3c85b
                      - id: 5ff5cc9bc1acf144d9106233
                      - id: 610001e7da283e36d0a0df9f
                      - id: 613b51c01f4b04615ba1d3be
                    vlanId: 10
                    status: READY
                    createdOn: '2022-04-05T13:50:30.491Z'
                    memberships: []
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /public-networks/{publicNetworkId}:
    parameters:
      - $ref: '#/components/parameters/publicNetworkIdPathParam'
    get:
      tags:
        - Public Networks
      description: Retrieve Public Network Details.
      summary: Get a Public Network.
      operationId: publicNetworksNetworkIdGet
      security:
        - OAuth2:
            - bmc.read
      responses:
        '200':
          description: Public Network Details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicNetwork'
              examples:
                PublicNetworkWithOnlyRequiredFields:
                  value:
                    id: 60472f76bbadb4f36541d2fd
                    name: Initial public network
                    location: PHX
                    ipBlocks: []
                    vlanId: 10
                    status: READY
                    createdOn: '2022-04-05T13:50:30.491Z'
                    memberships: []
                PublicNetworkOnlyWithoutIpBlocks:
                  value:
                    id: 60472f76bbadb4f36541d2fd
                    name: Initial public network
                    location: PHX
                    description: 'My first public network #1'
                    ipBlocks: []
                    vlanId: 10
                    status: READY
                    createdOn: '2022-04-05T13:50:30.491Z'
                    memberships: []
                PublicNetworkWithIpBlocks:
                  value:
                    id: 60472f76bbadb4f36541d2fd
                    name: Initial public network
                    location: PHX
                    description: 'My first public network #1'
                    ipBlocks:
                      - id: 60473a6115e34466c9f8f083
                      - id: 616e6ec6d66b406a45ab8797
                      - id: 617d2d128bacbb05aca2caeb
                      - id: 617d2da78bacbb05aca2caef
                      - id: 618e5383a835704f8c59522d
                      - id: 617d2f834dcf2869f8e4ef0b
                      - id: 5f325c71b8a7ef1473e3c85b
                      - id: 5ff5cc9bc1acf144d9106233
                      - id: 610001e7da283e36d0a0df9f
                      - id: 613b51c01f4b04615ba1d3be
                    vlanId: 10
                    status: READY
                    createdOn: '2022-04-05T13:50:30.491Z'
                    memberships: []
                PublicNetworkWithIpBlocksAndServers:
                  value:
                    id: 60472f76bbadb4f36541d2fd
                    name: Initial public network
                    location: PHX
                    description: 'My first public network #1'
                    ipBlocks:
                      - id: 60473a6115e34466c9f8f083
                      - id: 616e6ec6d66b406a45ab8797
                      - id: 617d2d128bacbb05aca2caeb
                      - id: 617d2da78bacbb05aca2caef
                      - id: 618e5383a835704f8c59522d
                      - id: 617d2f834dcf2869f8e4ef0b
                      - id: 5f325c71b8a7ef1473e3c85b
                      - id: 5ff5cc9bc1acf144d9106233
                      - id: 610001e7da283e36d0a0df9f
                      - id: 613b51c01f4b04615ba1d3be
                    vlanId: 10
                    status: READY
                    createdOn: '2022-04-05T13:50:30.491Z'
                    memberships:
                      - resourceId: 6128d3754b478b76ee8b3cdd
                        resourceType: server
                        ips:
                          - 10.111.14.123
                      - resourceId: 5feae6b0b00bfb14eda82fc7
                        resourceType: server
                        ips:
                          - 10.111.14.200
                          - 10.111.14.201
                          - 10.111.14.202
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
    patch:
      tags:
        - Public Networks
      description: Update Public Network's Details.
      summary: Update Public Network's Details.
      operationId: publicNetworksNetworkIdPatch
      security:
        - OAuth2:
            - bmc
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicNetworkModify'
            examples:
              PublicNetworkModifyWithNameAndDescription:
                value:
                  name: My public network
                  description: The new description of my public network
              PublicNetworkModifyWithNameOnly:
                value:
                  name: My public network
              PublicNetworkModifyWithDescriptionOnly:
                value:
                  description: The new description of my public network
      responses:
        '200':
          description: Network successfully updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicNetwork'
              example:
                id: 60472f76bbadb4f36541d2fd
                name: My public network
                location: PHX
                description: The new description of my public network
                ipBlocks: []
                vlanId: 10
                status: READY
                createdOn: '2022-04-05T13:50:30.491Z'
                memberships: []
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - Public Networks
      description: Delete Public Network. The request is accepted only if no resources are members of this network. The IP Block(s) will be freed and can be re-used in the future.
      summary: Delete a Public Network.
      operationId: publicNetworksNetworkIdDelete
      security:
        - OAuth2:
            - bmc
      responses:
        '204':
          description: The Public Network has been deleted.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /public-networks/{publicNetworkId}/ip-blocks:
    parameters:
      - $ref: '#/components/parameters/publicNetworkIdPathParam'
    post:
      tags:
        - Public Networks
      description: Adds an IP block to this public network.
      summary: Adds an IP block to this public network.
      operationId: publicNetworksNetworkIdIpBlocksPost
      security:
        - OAuth2:
            - bmc
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicNetworkIpBlock'
            example:
              id: 60473a6115e34466c9f8f083
      responses:
        '202':
          description: The specified IP block is being added to the public network.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicNetworkIpBlock'
              example:
                id: 60473a6115e34466c9f8f083
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /public-networks/{publicNetworkId}/ip-blocks/{ipBlockId}:
    parameters:
      - $ref: '#/components/parameters/publicNetworkIdPathParam'
      - $ref: '#/components/parameters/ipBlockIdPathParam'
    delete:
      tags:
        - Public Networks
      description: Removes the IP Block from the Public Network.<br> Please ensure that no resource members within this network have any IPs assigned from the IP Block being removed.<br> Defining `force` query parameter allows resource assigned IP block to be removed anyway.  As a result, traffic addressed to any IP within the block will not be routed to this network anymore.
      summary: Removes the IP Block from the Public Network.
      operationId: publicNetworksNetworkIdIpBlocksIpBlockIdDelete
      security:
        - OAuth2:
            - bmc
      parameters:
        - $ref: '#/components/parameters/forceQueryParam'
      responses:
        '202':
          description: The specified IP block is being removed from the Public Network.
          content:
            application/json:
              schema:
                type: string
                description: The specified IP block is being removed from the Public Network.
                example: The specified IP block is being removed from the Public Network.
              example: The specified IP block is being removed from the Public Network.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.phoenixnap.com/auth/realms/BMC/protocol/openid-connect/token
          scopes:
            bmc: Grants full access to bmc-api.
            bmc.read: Grants read only access to bmc-api.
  schemas:
    PrivateNetwork:
      type: object
      description: Private Network details.
      required:
        - id
        - name
        - vlanId
        - type
        - location
        - locationDefault
        - servers
        - memberships
        - status
        - createdOn
      properties:
        id:
          description: The private network identifier.
          type: string
          example: 604721852cf65253d151528b
        name:
          description: The friendly name of this private network.
          type: string
          minLength: 1
          maxLength: 100
          example: Sample Network
        description:
          description: The description of this private network.
          type: string
          maxLength: 250
          example: Further details on the network
        vlanId:
          description: The VLAN of this private network.
          type: integer
          example: 10
        type:
          description: The type of the private network.
          type: string
          example: PRIVATE
        location:
          description: The location of this private network.
          type: string
          example: PHX
        locationDefault:
          description: Identifies network as the default private network for the specified location.
          type: boolean
          example: true
        cidr:
          description: IP range associated with this private network in CIDR notation.
          type: string
          example: 10.0.0.0/24
        servers:
          type: array
          items:
            $ref: '#/components/schemas/PrivateNetworkServer'
          deprecated: true
        memberships:
          description: A list of resources that are members of this private network.
          type: array
          items:
            $ref: '#/components/schemas/NetworkMembership'
        status:
          description: 'The status of the private network. Can have one of the following values: `BUSY` or `READY`.'
          type: string
          example: READY
        createdOn:
          description: Date and time when this private network was created.
          type: string
          format: date-time
          example: '2022-04-07T13:30:30.491Z'
    PrivateNetworkServer:
      type: object
      description: Server details linked to the Private Network.
      required:
        - id
        - ips
      properties:
        id:
          description: The server identifier.
          type: string
          example: 603f3e995c18d515cda9c4f8
        ips:
          type: array
          description: List of private IPs associated to the server.
          items:
            type: string
            example: 10.0.0.2
          example:
            - 10.0.0.2
            - 10.0.0.3
    PrivateNetworkCreate:
      type: object
      description: Details of Private Network to be created.
      required:
        - name
        - location
      properties:
        name:
          description: The friendly name of this private network. This name should be unique.
          type: string
          minLength: 1
          maxLength: 100
          example: Sample Network
        description:
          description: The description of this private network.
          type: string
          maxLength: 250
          example: Further details on the network
        location:
          description: The location of this private network. Supported values are `PHX`, `ASH`, `SGP`, `NLD`, `CHI`, `SEA` and `AUS`.
          type: string
          example: PHX
        locationDefault:
          description: Identifies network as the default private network for the specified location.
          type: boolean
          default: false
          example: true
        vlanId:
          description: The VLAN that will be assigned to this network.
          type: integer
          minimum: 2
          maximum: 4094
          example: 10
        cidr:
          description: IP range associated with this private network in CIDR notation.<br> Setting the `force` query parameter to `true` allows you to skip assigning a specific IP range to network.
          type: string
          example: 10.0.0.0/24
    PrivateNetworkModify:
      type: object
      description: Object including details to be modified in the Private Network.
      required:
        - name
        - locationDefault
      properties:
        name:
          type: string
          description: A friendly name given to the private network. This name should be unique.
          minLength: 1
          maxLength: 100
          example: Sample network
        description:
          description: A description of this private network
          type: string
          maxLength: 250
          example: Further details on the network.
        locationDefault:
          description: Identifies network as the default private network for the specified location.
          type: boolean
          example: true
    PublicNetwork:
      type: object
      description: Public Network details.
      required:
        - id
        - name
        - location
        - ipBlocks
        - vlanId
        - memberships
        - status
        - createdOn
      properties:
        id:
          description: The public network identifier.
          type: string
          example: 604721852cf65253d151528b
        vlanId:
          description: The VLAN of this public network.
          type: integer
          example: 10
        memberships:
          description: A list of resources that are members of this public network.
          type: array
          items:
            $ref: '#/components/schemas/NetworkMembership'
        name:
          description: The friendly name of this public network.
          type: string
          minLength: 1
          maxLength: 100
          example: Sample Network
        location:
          description: The location of this public network. Supported values are `PHX`, `ASH`, `SGP`, `NLD`, `CHI`, `SEA` and `AUS`.
          type: string
          example: PHX
        description:
          description: The description of this public network.
          type: string
          maxLength: 250
          example: Further details on the network.
        status:
          description: 'The status of the public network. Can have one of the following values: `BUSY` or `READY`.'
          type: string
          example: READY
        createdOn:
          description: Date and time when this public network was created.
          type: string
          format: date-time
          example: '2022-04-05T13:50:30.491Z'
        ipBlocks:
          description: A list of IP Blocks that are associated with this public network.
          type: array
          items:
            $ref: '#/components/schemas/PublicNetworkIpBlock'
    PublicNetworkIpBlock:
      type: object
      description: The assigned IP block to the Public Network.
      required:
        - id
      properties:
        id:
          description: The IP Block identifier.
          type: string
          example: 60473a6115e34466c9f8f083
    PublicNetworkCreate:
      type: object
      description: Details of Public Network to be created.
      required:
        - name
        - location
      properties:
        name:
          description: The friendly name of this public network. This name should be unique.
          type: string
          minLength: 1
          maxLength: 100
          example: Sample Network
        description:
          description: The description of this public network.
          type: string
          maxLength: 250
          example: Further details on the network.
        location:
          description: The location of this public network. Supported values are `PHX`, `ASH`, `SGP`, `NLD`, `CHI`, `SEA` and `AUS`.
          type: string
          example: PHX
        vlanId:
          description: The VLAN that will be assigned to this network.
          type: integer
          minimum: 2
          maximum: 4094
          example: 10
        ipBlocks:
          description: A list of IP Blocks that will be associated with this public network.
          type: array
          maxItems: 10
          items:
            $ref: '#/components/schemas/PublicNetworkIpBlock'
    PublicNetworkModify:
      type: object
      description: Public Network Modifiable Details.
      properties:
        name:
          description: A friendly name given to the network. This name should be unique.
          type: string
          minLength: 1
          maxLength: 100
          example: Sample Network
        description:
          description: The description of this public network
          type: string
          maxLength: 250
          example: Further details on the network.
    NetworkMembership:
      type: object
      description: Resource details linked to the Network.
      required:
        - resourceId
        - resourceType
        - ips
      properties:
        resourceId:
          description: The resource identifier.
          type: string
          example: 603f3e995c18d515cda9c4f8
        resourceType:
          description: The resource's type.
          type: string
          example: server
        ips:
          type: array
          description: List of IPs associated to the resource.
          items:
            type: string
          example:
            - 10.111.14.104
            - 10.111.14.105
            - 10.111.14.106
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          readOnly: true
          description: The description detailing the cause of the error code.
        validationErrors:
          type: array
          items:
            type: string
          readOnly: true
          description: Validation errors, if any.
  responses:
    BadRequest:
      description: The request failed due to wrong data. Please check the provided parameters and try again.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: The request failed due to invalid credentials. Please check the provided credentials and try again.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: The request failed since this resource cannot be accessed by the provided credentials.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: The server encountered an unexpected condition that prevented it from fulfilling the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: The request failed since the resource could not been found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict:
      description: The resource is in an incompatible state.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  parameters:
    forceQueryParam:
      name: force
      in: query
      description: Query parameter controlling advanced features availability. Currently applicable for networking. It is advised to use with caution since it might lead to unhealthy setups.
      required: false
      schema:
        type: boolean
        default: false
      example: true
    privateNetworkIdPathParam:
      in: path
      name: privateNetworkId
      required: true
      schema:
        type: string
      description: The private network identifier.
      example: 603f3b2cfcaf050643b89a4b
    publicNetworkIdPathParam:
      in: path
      name: publicNetworkId
      required: true
      schema:
        type: string
      description: The Public Network identifier.
      example: 603f3b2cfcaf050643b89a4b
    ipBlockIdPathParam:
      in: path
      name: ipBlockId
      required: true
      schema:
        type: string
      description: The IP Block identifier.
      example: 6047127fed34ecc3ba8402d2
