openapi: 3.0.2
info:
  contact:
    email: support@phoenixnap.com
    name: PhoenixNAP Team
    url: https://phoenixnap.com/
  description: |
    Public IP blocks are a set of contiguous IPs that allow you to access your servers or networks from the internet.
    Use the IP Addresses API to request and delete IP blocks.<br>
    <br>
    <span class='pnap-api-knowledge-base-link'>
    Knowledge base articles to help you can be found
    <a href='https://phoenixnap.com/kb/public-ip-management#bmc-public-ip-allocations-api' target='_blank'>here</a>
    </span><br>
    <br>
    <b>All URLs are relative to (https://api.phoenixnap.com/ips/v1/)</b>
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://phoenixnap.com/infrastructure-solutions/legal-it/privacy-shield-compliant-privacy-policy
  title: IP Addresses API
  version: "1.0"
servers:
- url: https://api.phoenixnap.com/ips/v1
security:
- OAuth2:
  - bmc
  - bmc.read
tags:
- description: Public IP Block operations.
  name: IP Blocks
paths:
  /ip-blocks:
    get:
      description: List all IP Blocks.
      operationId: ipBlocksGet
      parameters:
      - description: List of tags, in the form tagName.tagValue, to filter by.
        example:
        - env.dev
        - loc.phx
        explode: true
        in: query
        name: tag
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/IpBlock'
                type: array
          description: IP Blocks list.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to invalid credentials. Please check
            the provided credentials and try again.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since this resource cannot be accessed by
            the provided credentials.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - OAuth2:
        - bmc.read
      summary: List IP Blocks.
      tags:
      - IP Blocks
    post:
      description: Request an IP Block. An IP Block is a set of contiguous IPs that
        can be assigned to other resources such as servers.
      operationId: ipBlocksPost
      requestBody:
        content:
          application/json:
            example:
              cidrBlockSize: /28
              location: PHX
              description: 'IP Block #1 used for publicly accessing server #1.'
            schema:
              $ref: '#/components/schemas/IpBlockCreate'
      responses:
        "201":
          content:
            application/json:
              example:
                id: 6047127fed34ecc3ba8402d2
                cidr: 1.1.1.0/28
                location: PHX
                cidrBlockSize: /28
                status: unassigned
                description: 'IP Block #1 used for publicly accessing server #1.'
                isBringYourOwn: false
                createdOn: 2021-03-13T20:24:32.491Z
              schema:
                $ref: '#/components/schemas/IpBlock'
          description: IP Block created.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to wrong data. Please check the provided
            parameters and try again.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to invalid credentials. Please check
            the provided credentials and try again.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since this resource cannot be accessed by
            the provided credentials.
        "406":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: No server available of type server.type.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - OAuth2:
        - bmc
      summary: Create an IP Block.
      tags:
      - IP Blocks
  /ip-blocks/{ipBlockId}:
    delete:
      description: Delete an IP Block. An IP Block can only be deleted if not assigned
        to any resource.
      operationId: ipBlocksIpBlockIdDelete
      parameters:
      - description: The IP Block identifier.
        example: 6047127fed34ecc3ba8402d2
        explode: false
        in: path
        name: ipBlockId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteIpBlockResult'
          description: IP Block deleted.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to invalid credentials. Please check
            the provided credentials and try again.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since this resource cannot be accessed by
            the provided credentials.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - OAuth2:
        - bmc
      summary: Delete IP Block.
      tags:
      - IP Blocks
    get:
      description: Get IP Block.
      operationId: ipBlocksIpBlockIdGet
      parameters:
      - description: The IP Block identifier.
        example: 6047127fed34ecc3ba8402d2
        explode: false
        in: path
        name: ipBlockId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IpBlock'
          description: Specific IP Block details.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to invalid credentials. Please check
            the provided credentials and try again.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since this resource cannot be accessed by
            the provided credentials.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - OAuth2:
        - bmc.read
      summary: Get IP Block.
      tags:
      - IP Blocks
    patch:
      description: Update IP Block's details.
      operationId: ipBlocksIpBlockIdPatch
      parameters:
      - description: The IP Block identifier.
        example: 6047127fed34ecc3ba8402d2
        explode: false
        in: path
        name: ipBlockId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            example:
              description: Ip Block description
            schema:
              $ref: '#/components/schemas/IpBlockPatch'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IpBlock'
          description: Updated IpBlock.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to wrong data. Please check the provided
            parameters and try again.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to invalid credentials. Please check
            the provided credentials and try again.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since this resource cannot be accessed by
            the provided credentials.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since the resource could not been found.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - OAuth2:
        - bmc
      summary: Update IP block.
      tags:
      - IP Blocks
  /ip-blocks/{ipBlockId}/tags:
    put:
      description: Overwrites tags assigned for IP Block and unassigns any tags not
        part of the request.
      operationId: ipBlocksIpBlockIdTagsPut
      parameters:
      - description: The IP Block identifier.
        example: 6047127fed34ecc3ba8402d2
        explode: false
        in: path
        name: ipBlockId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              example:
              - name: stage
                value: beta
              - name: group
                value: discountId
              items:
                $ref: '#/components/schemas/TagAssignmentRequest'
              type: array
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IpBlock'
          description: IP Blocks tags set.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to wrong data. Please check the provided
            parameters and try again.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed due to invalid credentials. Please check
            the provided credentials and try again.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request failed since this resource cannot be accessed by
            the provided credentials.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The server encountered an unexpected condition that prevented
            it from fulfilling the request.
      security:
      - OAuth2:
        - bmc
      summary: Overwrite tags assigned for IP Block.
      tags:
      - IP Blocks
components:
  parameters:
    ipBlockIdPathParam:
      description: The IP Block identifier.
      example: 6047127fed34ecc3ba8402d2
      explode: false
      in: path
      name: ipBlockId
      required: true
      schema:
        type: string
      style: simple
  responses:
    Unauthorized:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The request failed due to invalid credentials. Please check the
        provided credentials and try again.
    Forbidden:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The request failed since this resource cannot be accessed by the
        provided credentials.
    InternalServerError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The server encountered an unexpected condition that prevented it
        from fulfilling the request.
    BadRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The request failed due to wrong data. Please check the provided
        parameters and try again.
    NotAccepted:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: No server available of type server.type.
    NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The request failed since the resource could not been found.
  schemas:
    IpBlockPatch:
      description: IP Block patch.
      example:
        description: Ip Block allocation.
      properties:
        description:
          description: The description of the Ip Block.
          example: Ip Block allocation.
          maxLength: 250
          type: string
      type: object
    IpBlockCreate:
      description: IP Block Request.
      example:
        description: 'IP Block #1 used for publicly accessing server #1.'
        location: PHX
        cidrBlockSize: /30
        tags:
        - name: stage
          value: beta
        - name: group
          value: discounted
      properties:
        location:
          description: IP Block location ID. Currently this field should be set to
            `PHX`, `ASH`, `SGP`, `NLD`, `CHI`, `SEA` or `AUS`.
          example: PHX
          type: string
        cidrBlockSize:
          description: CIDR IP Block Size. Currently this field should be set to either
            `/31`, `/30`, `/29` or `/28`. For a larger Block Size contact support.
          example: /30
          type: string
        description:
          description: The description of the IP Block.
          example: 'IP Block #1 used for publicly accessing server #1.'
          maxLength: 250
          type: string
        tags:
          description: Tags to set to ip-block, if any.
          example:
          - name: stage
            value: beta
          - name: group
            value: discounted
          items:
            $ref: '#/components/schemas/TagAssignmentRequest'
          type: array
      required:
      - cidrBlockSize
      - location
      type: object
    IpBlock:
      description: IP Block Details.
      example:
        description: 'IP Block #1 used for publicly accessing server #1.'
        isBringYourOwn: false
        location: PHX
        cidr: 1.1.1.0/31
        id: 6047127fed34ecc3ba8402d2
        assignedResourceId: 6047127fed34ecc3ba8402d2
        assignedResourceType: server
        createdOn: 2021-03-13T20:24:32.491Z
        cidrBlockSize: /30
        status: unassigned
        tags:
        - name: stage
          value: beta
        - name: group
          value: discounted
      properties:
        id:
          description: IP Block identifier.
          example: 6047127fed34ecc3ba8402d2
          type: string
        location:
          description: IP Block location ID. Currently this field should be set to
            `PHX`, `ASH`, `SGP`, `NLD`, `CHI`, `SEA` or `AUS`.
          example: PHX
          type: string
        cidrBlockSize:
          description: CIDR IP Block Size. Currently this field should be set to either
            `/31`, `/30`, `/29`, `/28`, `/27`, `/26`, `/25`, `/24`, `/23` or `/22`.
          example: /30
          type: string
        cidr:
          description: The IP Block in CIDR notation.
          example: 1.1.1.0/31
          type: string
        status:
          description: The status of the IP Block.
          example: unassigned
          type: string
        assignedResourceId:
          description: ID of the resource assigned to the IP Block.
          example: 6047127fed34ecc3ba8402d2
          type: string
        assignedResourceType:
          description: Type of the resource assigned to the IP Block.
          example: server
          type: string
        description:
          description: The description of the IP Block.
          example: 'IP Block #1 used for publicly accessing server #1.'
          maxLength: 250
          type: string
        tags:
          description: The tags assigned if any.
          example:
          - name: stage
            value: beta
          - name: group
            value: discounted
          items:
            $ref: '#/components/schemas/TagAssignment'
          type: array
        isBringYourOwn:
          description: True if the IP block is a `bring your own` block.
          example: false
          type: boolean
        createdOn:
          description: Date and time when the IP block was created.
          example: 2021-03-13T20:24:32.491Z
          format: date-time
          type: string
      required:
      - cidr
      - cidrBlockSize
      - createdOn
      - id
      - isBringYourOwn
      - location
      - status
      type: object
    DeleteIpBlockResult:
      description: Result of a successful delete action.
      example:
        result: IP Block has been deleted.
        ipBlockId: 6047127fed34ecc3ba8402d2
      properties:
        result:
          description: IP Block has been deleted.
          example: IP Block has been deleted.
          type: string
        ipBlockId:
          description: The unique identifier of the IP Block.
          example: 6047127fed34ecc3ba8402d2
          type: string
      required:
      - ipBlockId
      - result
      type: object
    TagAssignment:
      description: Tag assigned to resource.
      properties:
        id:
          description: The unique id of the tag.
          example: 60ffafcdffb8b074c7968dad
          type: string
        name:
          description: The name of the tag.
          example: Environment
          type: string
        value:
          description: The value of the tag assigned to the resource.
          example: PROD
          type: string
        isBillingTag:
          description: Whether or not to show the tag as part of billing and invoices
          example: true
          type: boolean
        createdBy:
          description: Who the tag was created by.
          enum:
          - USER
          - SYSTEM
          type: string
      required:
      - id
      - isBillingTag
      - name
      type: object
    Error:
      properties:
        message:
          description: The description detailing the cause of the error code.
          readOnly: true
          type: string
        validationErrors:
          description: Validation errors, if any.
          items:
            type: string
          readOnly: true
          type: array
      required:
      - message
      type: object
    TagAssignmentRequest:
      description: Tag request to assign to resource.
      example:
        name: Environment
        value: PROD
      properties:
        name:
          description: 'The name of the tag. Tag names are case-sensitive, and should
            be composed of a maximum of 100 characters including UTF-8 Unicode letters,
            numbers, and the following symbols: ''-'', ''_''. Regex: [A-zÀ-ú0-9_-]{1,100}.'
          example: Environment
          type: string
        value:
          description: 'The value of the tag assigned to the resource. Tag values
            are case-sensitive, and should be composed of a maximum of 100 characters
            including UTF-8 Unicode letters, numbers, and the following symbols: ''-'',
            ''_''. Regex: [A-zÀ-ú0-9_-]{1,100}.'
          example: PROD
          type: string
      required:
      - name
      type: object
  securitySchemes:
    OAuth2:
      flows:
        clientCredentials:
          scopes:
            bmc: Grants full access to bmc-api.
            bmc.read: Grants read only access to bmc-api.
          tokenUrl: https://auth.phoenixnap.com/auth/realms/BMC/protocol/openid-connect/token
      type: oauth2
